const path                 = require("path");
const Merge                = require("webpack-merge");
const CommonConfig         = require("./webpack.common.config.js");
const MiniCssExtractPlugin = require("mini-css-extract-plugin")
const html_files           = require("./html_files");
const copy_assets          = require("./copy_assets");


const html_files_plugins = html_files({
  minify: {
    "caseSensitive": false,
    "collapseBooleanAttributes": true,
    "collapseInlineTagWhitespace": false,
    "collapseWhitespace": true,
    "conservativeCollapse": true,
    "continueOnParseError": false,
    "decodeEntities": true,
    "html5": true,
    "ignoreCustomFragments": [],
    "includeAutoGeneratedTags": false,
    "keepClosingSlash": false,
    "maxLineLength": 0,
    "minifyCSS": true,
    "minifyJS": true,
    "preserveLineBreaks": false,
    "preventAttributesEscaping": false,
    "processConditionalComments": true,
    "processScripts": [ ],
    "removeAttributeQuotes": false,
    "removeComments": true,
    "removeEmptyAttributes": true,
    "removeEmptyElements": true,
    "removeOptionalTags": false,
    "removeRedundantAttributes": true,
    "removeScriptTypeAttributes": true,
    "removeStyleLinkTypeAttributes": true,
    "removeTagWhitespace": false,
    "sortAttributes": true,
    "sortClassName": true,
    "trimCustomFragments": true,
    "useShortDoctype": true
  }
});

const plugins = [
  new MiniCssExtractPlugin({ filename: "styles-[contenthash].css" })
].concat(html_files_plugins).concat(copy_assets);

module.exports = Merge(CommonConfig, {
  output: {
    path: path.join(__dirname, "../production"),
    filename: "bundle-[contenthash].js"
  },
  plugins: plugins,
  optimization: {
    minimize: true
  }
});
